version: '3.5'
services:
  mc_creative:
    container_name: mc_creative
    build:
      context: ../minecraft-world/
    restart: 'unless-stopped'
    networks:
      minecraft-net:
        aliases:
          - 'mc_creative'
          - 'creative'
    environment:
      DIFFICULTY: 'peaceful'
      MODE: 1
      GENERATE_STRUCTURES: "FALSE"

      # SERVER CONFIG
      MAX_WORLD_SIZE: 10000
      LEVEL_TYPE: 'flat'
    volumes:
      - ${MINECRAFT_DIR}/worlds/mc-creative/data:/data
    tty: true
    stdin_open: true

networks:
  minecraft-net:
    external:
      name: minecraft-net
