version: '3.5'

services:
  proxy:
    image: itzg/bungeecord
    container_name: proxy
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    networks:
      minecraft-net:
        aliases:
          - 'mc_proxy'
          - 'proxy'
    ports:
      - "25565:25577"
    volumes:
      - ./proxy/velocity.toml:/config/velocity.toml
      - ./proxy/forwarding.secret:/config/forwarding.secret
      - proxy:/server

volumes:
  proxy: {}

networks:
  minecraft-net:
    external:
      name: minecraft-net
